openapi: '3.0.3'
info:
  title: Book REST Example
  description: "Documentation REST API Book"
  version: '1.0'
servers:
  - url: http://localhost:3000/v1
components:
  schemas:
    DtoCreateOrUpdate:
      type: object
      properties:
        title:
          type: string
          example: Inspiration Quotes by Aji
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
                example: 401
              message:
                type: string
                example: failed
              error:
                type: string
                example: invalid signature
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
                example: 404
              message:
                type: string
                example: failed
              error:
                type: string
                example: record not found
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
                example: 500
              message:
                type: string
                example: failed
              error:
                type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: authorization
paths:
  /books:
    post:
      summary: Create book
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DtoCreateOrUpdate"
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: success
                  data:
                    properties:
                      id:
                        type: number
                        example: 1
                      title:
                        type: string
                        example: Inspiration Quotes by Aji
                      created_at:
                        type: string
                        example: 2022-08-30T01:04:26.862+07:00
                      updated_at:
                        type: string
                        example: 2022-08-30T01:04:26.862+07:00
        '401':
          $ref: "#/components/responses/Unauthorized"
        '500':
          $ref: "#/components/responses/InternalServerError"
    get:
      summary: Get book all
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        title:
                          type: string
                          example: Inspiration Quotes by Aji
        '401':
          $ref: "#/components/responses/Unauthorized"
        '500':
          $ref: "#/components/responses/InternalServerError"

  /books/{bookId}:
    get:
      summary: Get book by id
      security:
        - ApiKeyAuth: []
      parameters:
        - name: bookId
          in: path
          required: true
          description: ID Book.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: success
                  data:
                    properties:
                      id:
                        type: number
                        example: 1
                      title:
                        type: string
                        example: Inspiration Quotes by Aji
                      created_at:
                        type: string
                        example: 2022-08-30T01:04:26.862+07:00
                      updated_at:
                        type: string
                        example: 2022-08-30T01:07:34.824+07:00
        '401':
          $ref: "#/components/responses/Unauthorized"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/InternalServerError"
    put:
      summary: Update book
      security:
        - ApiKeyAuth: []
      parameters:
        - name: bookId
          in: path
          required: true
          description: ID Book.
          schema:
            type : integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Inspiration Quotes by Aji
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: success
                  data:
                    properties:
                      id:
                        type: number
                        example: 1
                      title:
                        type: string
                        example: Inspiration Quotes by Aji
                      created_at:
                        type: string
                        example: 2022-08-30T01:04:26.862+07:00
                      updated_at:
                        type: string
                        example: 2022-08-30T01:07:34.824+07:00
        '401':
          $ref: "#/components/responses/Unauthorized"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/InternalServerError"
    delete:
      summary: Delete book
      security:
        - ApiKeyAuth: []
      parameters:
        - name: bookId
          in: path
          required: true
          description: ID Book.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: success
                  data:
                    properties:
                      id:
                        type: number
                        example: 1
                      title:
                        type: string
                        example: Inspiration Quotes by Aji
                      created_at:
                        type: string
                        example: 2022-08-30T01:04:26.862+07:00
                      updated_at:
                        type: string
                        example: 2022-08-30T01:07:34.824+07:00
        '401':
          $ref: "#/components/responses/Unauthorized"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/InternalServerError"

                    